### PR TITLE
Fixing the ldap config and putting ConfigureCommand in.

### LINKED ISSUE #1: Fix ldap client automation
ldap client usage requires modifications to the web context policy configuration

### PR DESCRIPTION
**Pull request by brjeter**
Automates ldap client setup and adds ConfigureCommand prototype usage

fixes #1

### CODE REVIEW

File: alpine/entrypoint/pre_start.sh [hunk 1]
```diff
@@ -36,26 +36,8 @@ fi
...
-
-  echo "Adding $_appCount startup apps"
-
-  for (( i=1; i<=$_appCount; i++ ))
-  do
-    _currentApp=$(echo $STARTUP_APPS | cut -d ";" -f $i)
-    echo "Adding: $_currentApp"
-    props set $_currentApp '' $APP_HOME/etc/org.codice.ddf.admin.applicationlist.properties
-  done
+  props set org.codice.ddf.ldap.port $LDAP_PORT $APP_HOME/etc/system.properties
```
Comment (oconnormi) [inline alpine/entrypoint/pre_start.sh]: Probably should wrap this in an `if [ -n "$LDAP_PORT" ]; then...` check in case the ldap port isn't specified and set the property to the default value (i'm assuming the property doesn't exist until after this line)

File: alpine/entrypoint/post_start.sh [hunk 2]
```diff
@@ -5,47 +5,13 @@ do
...
 done
 
-if [ -n "$INSTALL_FEATURES" ]; then
-  if [[ $INSTALL_FEATURES == *";"* ]]; then
-  _featureCount=$[$(echo $INSTALL_FEATURES | grep -o ";" | wc -l) + 1]
-  else
-    _featureCount=1
-  fi
+$APP_HOME/bin/client waitForReady -r 12 -d 10
+$APP_HOME/bin/client admin:configure /opt/ddfConfig.json -r 12 -d 10
```
Comment (oconnormi) [inline alpine/entrypoint/post_start.sh]: What happens if a config file isn't provided by a downstream container or in a volume mount? Should this be wrapped in a check for an env var pointing to the file in case of a container run that isn't using an automated install?

File: alpine/entrypoint/post_start.sh [hunk 3]
```diff
@@ -5,47 +5,13 @@ do
    [[ "${LOGLINE}" == *"Binding bundle: [landing-page"* ]] && pkill -P $$ tail
 done
 
-if [ -n "$INSTALL_FEATURES" ]; then
-  if [[ $INSTALL_FEATURES == *";"* ]]; then
```
Comment (oconnormi) [inline alpine/entrypoint/post_start.sh]: I'm thinking it might be valuable to leave the `feature:install` and `feature:uninstall` cases in here as well for non ConfigureCommand scenarios. (like if we ever wanted to use a regular karaf container for something for some reason)

File: alpine/entrypoint/pre_start.sh [hunk 4]
```diff
@@ -36,26 +36,8 @@ fi
 # TODO: add more fine grained ldap configuration support
 if [ -n "$LDAP_HOST" ]; then
   echo "Remote LDAP HOST: $LDAP_HOST configured"
-  cp $ENTRYPOINT_HOME/config/ldap/*.config $APP_HOME/etc/
   props set org.codice.ddf.ldap.hostname $LDAP_HOST $APP_HOME/etc/system.properties
-fi
-
-if [ -n "$STARTUP_APPS" ]; then
```
Comment (oconnormi) [inline alpine/entrypoint/pre_start.sh:43]: Glad to see this going away, so unreliable 👍

**Review by oconnormi — CHANGES_REQUESTED** [review]

File: alpine/entrypoint/post_start.sh (hunk 2 above)
Comment (brjeter) [reply alpine/entrypoint/post_start.sh]: This is definitely subjective, but I think I'd rather avoid another environment variable. If they're running this container on a distribution without the ConfigureCommand, it will just say "command not found" and move on. If the json config file doesn't exist, nothing will happen. So this call is very harmless if something is missing.

File: alpine/entrypoint/post_start.sh (hunk 3 above)
Comment (brjeter) [reply alpine/entrypoint/post_start.sh]: 👍

**Review by oconnormi — APPROVED** [review]
